name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test with conda
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.11, 3.12]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: Yads
        environment-file: environment.yml
        auto-activate-base: false

    - name: Install dependencies
      run: conda env update --file environment.yml

    - name: Run tests
      run: |
        conda run -n Yads pytest -vvv tests
