name: Conda install

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.12.2
        activate-environment: Yads
        environment-file: environment.yml
        auto-activate-base: false

    - name: Install dependencies
      run: conda env update --file environment.yml

    - name: Run tests
      run: |
        conda run -n Yads pytest -vvv tests
